name: Locker - Lock stale issues and PRs
on:
  schedule:
    - cron: '0 9 * * *'

  workflow_dispatch:
    # Manual triggering through the GitHub UI, API, or CLI

permissions:
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose: 14
          daysSinceUpdate: 14
