name: Locker - Lock stale issues and PRs
on:
  schedule:
    - cron: '16 9 * * *' # Once per day, overnight PT, uncommon minute of hour

  workflow_dispatch:
    # Manual triggering through the GitHub UI, API, or CLI
    inputs:
      daysSinceClose:
        required: true
        default: "30"
      daysSinceUpdate:
        required: true
        default: "30"

permissions:
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "jeffhandley/github-triage-actions"
          path: ./actions
          ref: jeffhandley/locker-type
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose:  ${{ fromJson(inputs.daysSinceClose  || 0) }}
          daysSinceUpdate: ${{ fromJson(inputs.daysSinceUpdate || 0) }}
